apiVersion: v1
kind: Service 
metadata:
  name: mylinuxapp-lb-service
spec:
  type: LoadBalancer 
  selector:
    app: mylinuxapp
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port    