apiVersion: v1
kind: Service 
metadata:
  name: myapp1-headless-service
spec:
  #type: ClusterIP # ClusterIP, # NodePort, # LoadBalancer, # ExternalName
  clusterIP: None
  selector:
    app: myapp1
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port

## VERY IMPORTANT NODE
# 1. Headless Service directly sends traffic to Pod with Pod IP and Container Port. 
# 2. DNS resolution directly happens from headless service to Pod IP.



