apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service 
  labels:
    app: myapp1
spec:
  type: ClusterIP # ClusterIPis a default service in k8s
  selector:
    app: myapp1
  ports:
    - name: http
      port: 80 # ClusterIP Service Port
      targetPort: 80 # Container Port
